# Specify the version for docker-compose.yml
version: "3.8"

# add the serivces needed (postgres,go)
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: songs
      POSTGRES_PASSWORD: songs

      
      # use the default value POSTGRES_USER as a database name (user in this case.)
     
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
  go:
    container_name: go
    ports: 
      - "8080:8080"
    # build the Dockerfile, alternatively use an image.
    build:
      context: .
    depends_on:
      - "postgres"
volumes:
  dbdata: